/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proyecto1;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author Daniel
 */
public class GameForm extends javax.swing.JFrame {

    /**
     * Creates new form GameForm
     */
    Box casillas[]=new Box[30];
    MenuForm menu=new MenuForm();
    Player jugador[]=new Player[3];
    Ladders escalera[]=new Ladders[4];
    Snakes serpiente[]=new Snakes[4];
    int turn;
    int s;
    public GameForm() {
        initComponents();
        s=0;
        this.turn=0;
        this.setLocationRelativeTo(null);
        for (int i = 0; i < 6; i++) {
            casillas[i]=new Box(50, 450);
        }
        for (int i = 6; i < 12; i++) {
            casillas[i]=new Box(0, 350);
        }
        for (int i = 12; i < 18; i++) {
            casillas[i]=new Box();
            casillas[i].setY(280);
        }
        for (int i = 18; i < 24; i++) {
            casillas[i]=new Box(50, 200);
        }
        for (int i = 24; i < 30; i++) {
            casillas[i]=new Box(50, 100);
        }
        
        for (int i = 0; i < 3; i++) {
            jugador[i]=new Player();
            jugador[i].setPositon(casillas[0]);
        }
        for (int i = 0; i < 4; i++) {
            escalera[i]=new Ladders();
        }
        for (int i = 0; i < 4; i++) {
            serpiente[i]=new Snakes();
        }

        casillas[1].setX(150);
        casillas[2].setX(220);
        casillas[3].setX(320);
        casillas[4].setX(400);
        casillas[5].setX(480);
        casillas[6].setX(480);
        casillas[7].setX(400);
        casillas[8].setX(320);
        casillas[9].setX(220);
        casillas[10].setX(150);
        casillas[11].setX(50);
        casillas[12].setX(50);
        casillas[13].setX(150);
        casillas[14].setX(220);
        casillas[15].setX(320);
        casillas[16].setX(400);
        casillas[17].setX(480);
        casillas[18].setX(480);
        casillas[19].setX(400);
        casillas[20].setX(320);
        casillas[21].setX(220);
        casillas[22].setX(150);
        casillas[23].setX(50);
        casillas[24].setX(50);
        casillas[25].setX(150);
        casillas[26].setX(220);
        casillas[27].setX(320);
        casillas[28].setX(400);
        casillas[29].setX(480);
        escalera[0].setStart(casillas[2]);
        escalera[0].setEnd(casillas[21]);
        escalera[1].setStart(casillas[4]);
        escalera[1].setEnd(casillas[7]);
        escalera[2].setStart(casillas[10]);
        escalera[2].setEnd(casillas[25]);
        escalera[3].setStart(casillas[19]);
        escalera[3].setEnd(casillas[28]);
        serpiente[0].setStart(casillas[17]);
        serpiente[0].setEnd(casillas[4]);
        serpiente[1].setStart(casillas[19]);
        serpiente[1].setEnd(casillas[7]);;
        serpiente[2].setStart(casillas[21]);
        serpiente[2].setEnd(casillas[9]);
        serpiente[3].setStart(casillas[27]);
        serpiente[3].setEnd(casillas[1]);
        escalera[0].setPosition(21);
        escalera[1].setPosition(7);
        escalera[2].setPosition(25);
        escalera[3].setPosition(28);
        infoDados.setText("Tiro de Dados:"+0);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tirar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        infoDados = new javax.swing.JLabel();
        jLabelGanador = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Documents\\NetBeansProjects\\Proyecto1\\src\\main\\java\\com\\mycompany\\Assets\\img.jpg")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Daniel\\Documents\\NetBeansProjects\\Proyecto1\\src\\main\\java\\com\\mycompany\\Assets\\Dados.gif")); // NOI18N

        Tirar.setText("Tirar");
        Tirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TirarActionPerformed(evt);
            }
        });

        jButton1.setText("Moverse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        infoDados.setText("infodados");

        jLabelGanador.setFont(new java.awt.Font("Microsoft JhengHei Light", 2, 18)); // NOI18N

        jButton2.setText("Subir/Bajar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(Tirar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(infoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(59, 59, 59))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tirar)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(38, 38, 38)
                .addComponent(infoDados, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jLabelGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TirarActionPerformed
        // TODO add your handling code here:
               int random = (int) (Math.random() * 6 + 1);
            jugador[this.turn].setCounter(random);   
        infoDados.setText("Tiro de Dados:"+random);
    }//GEN-LAST:event_TirarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jugador[this.turn].getCounter()==29) {
            jLabelGanador.setText("GANADOR PLAYER "+(this.turn+1));
        }
        
        jugador[this.turn].setPositon(casillas[jugador[this.turn].getCounter()]);
        this.turn++;
        if (this.turn>=menu.getPlayers()) {
            this.turn=0;
        }
        if (s==0) {
            jugador[this.turn].setPositon(escalera[1].getStart());
            s++;
        }
        if (s==0) {
            jugador[this.turn].setPositon(serpiente[1].getStart());
            s++;
        }
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < menu.getPlayers(); i++) {
            for (int j = 0; j < 4; j++) {
                if (jugador[i].getPositon()==escalera[j].getStart()) {
                    jugador[i].setPositon(escalera[j].getEnd());
                    jugador[i].setCounter(escalera[j].getPosition(),true);
                    repaint();
                }
                if (jugador[i].getPositon()==serpiente[i].getStart()) {
                    jugador[i].setPositon(serpiente[j].getEnd());
                    jugador[i].setCounter(serpiente[j].getPosition(),true);
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tirar;
    private javax.swing.JLabel infoDados;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelGanador;
    // End of variables declaration//GEN-END:variables


    public void paint(Graphics g){
        super.paint(g);
        if (menu.getPlayers()==1) {
            g.setColor(Color.BLACK);
            g.fillOval(jugador[0].getPositon().getX(), jugador[0].getPositon().getY(), 40, 40);
        }
        if (menu.getPlayers()==2) {
            g.setColor(Color.BLACK);
            g.fillOval(jugador[0].getPositon().getX(), jugador[0].getPositon().getY(), 40, 40);
            g.setColor(Color.WHITE);
            g.fillOval(jugador[1].getPositon().getX(), jugador[1].getPositon().getY(), 40, 40);
        }
        if (menu.getPlayers()==3) {
            g.setColor(Color.BLACK);
            g.fillOval(jugador[0].getPositon().getX(), jugador[0].getPositon().getY(), 40, 40);
            g.setColor(Color.WHITE);
            g.fillOval(jugador[1].getPositon().getX(), jugador[1].getPositon().getY(), 40, 40);
            g.setColor(Color.pink);
            g.fillOval(jugador[2].getPositon().getX(), jugador[2].getPositon().getY(), 40, 40);
        }
       
    }
    

}

